### ISSUE TITLE
failing to create links

### ISSUE THREAD

**Issue by ksteward** [rb125/docsend_links#1]
I was so hopeful this tool would work, but it throws an exception.  It *is* successful in credentialing in, locating the document, but then throws this exception (perhaps suggesting it needs updated HTML parsing maybe because DocSend changed since this script created?):

`Traceback (most recent call last):
  File "/home/ksteward/projects/idw/docsend_links/bulk_links.py", line 34, in <module>
    driver.find_element(By.ID, "login_user_email").send_keys(docsend_email)
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="login_user_email"]"}`

Thoughts?

**Comment by rb125** [comment]
Yea that sounds about right. I can look into it over the weekend. Feel free to send a PR if you’d like to take a jab at it yourself

**Comment by ksteward** [comment]
Additional exception being seen:  

Enter your docsend email:xxxxxxxxxxxxxxx
Enter your docsend password: xxxxxxxxxx
Enter link to your docsend document:https://docsend.com/documents/xxxxxxxx
[WDM] - Downloading: 100%|█████████████████████████████████████████████████████| 6.75M/6.75M [00:01<00:00, 5.15MB/s]
<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>ERROR: The request could not be satisfied</title>
</head><body>
<h1>403 ERROR</h1>
<h2>The request could not be satisfied.</h2>
<hr noshade="" size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<br clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<br clear="all">
<hr noshade="" size="1px">
<pre>Generated by cloudfront (CloudFront)
Request ID: CHYnz2pwqbL8YtajM_8WbxAJQwFBcWI86NOb4qkw75LpOOhSigvYFg==
</pre>
<address>
</address>
</body></html>
Traceback (most recent call last):
  File "/home/ksteward/projects/idw/docsend_links/./bulk_links.py", line 44, in <module>
    driver.find_element(By.ID, "login_user_password").send_keys(docsend_password)
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/ksteward/projects/idw/docsend_links/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="login_user_password"]"}
  (Session info: headless chrome=112.0.5615.165)
Stacktrace:
#0 0x561001155fe3 <unknown>
#1 0x561000e94d36 <unknown>
#2 0x561000ed1c4d <unknown>
#3 0x561000ed1d61 <unknown>
#4 0x561000f0d6a4 <unknown>
#5 0x561000ef28ed <unknown>
#6 0x561000f0b232 <unknown>
#7 0x561000ef2693 <unknown>
#8 0x561000ec503a <unknown>
#9 0x561000ec617e <unknown>
#10 0x561001117dbd <unknown>
#11 0x56100111bc6c <unknown>
#12 0x5610011254b0 <unknown>
#13 0x56100111cd63 <unknown>
#14 0x5610010efc35 <unknown>
#15 0x561001140138 <unknown>
#16 0x5610011402c7 <unknown>
#17 0x56100114e093 <unknown>
#18 0x7fc01f9366ba start_thread

My guess is Cloudfront is blocking the fetching.

Note:  When I try to login to the DocSend web page, it recognizes that I have a Dropbox account and then has me authenticate with Dropbox on another web page.  Not sure if that is some of what is going on.

I also wrapped the failed `driver.find_element(By.ID, "login_user_email").send_keys(docsend_email)` to capture the screenshot like:
print(driver.page_source)
try:
    driver.find_element(By.ID, "login_user_email").send_keys(docsend_email)
except:
    driver.save_screenshot('screenshot.png') 

and got the attached screenshot.

![screenshot](https://github.com/user-attachments/assets/3b6090ac-ace8-485d-875d-edc98837e37e)

I'm not very experienced with selenium, so just hoping this helps diagnose the problem.

thanks Rahul

**Comment by rb125** [comment]
Ah! docsend's blocking automated scripts, will need to use the browser's session object to bypass login altogether and directly access the document. I'll update the script with the necessary changes.

**Comment by ksteward** [comment]
Thanks Rahul!  This is beyond my expertise, so your fixing this is really appreciated!

cheers,

-keith
